default_language_version:
  python: python3

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        args: [ "--py39-plus" ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: setup.cfg
      - id: end-of-file-fixer
        exclude: ".ipynb"
      - id: check-json
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
      - id: debug-statements
      - id: pretty-format-json
        args: ['--autofix', '--no-ensure-ascii', '--no-sort-keys']
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: setup.cfg, setup.py, .git, __pycache__, old, build, dist
        additional_dependencies: [ 'flake8-docstrings' ]
        args:
          - "--docstring-convention=numpy"
          - "--max-line-length=120"
          - "--ignore=E302"
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ '--settings-file=setup.cfg', "--add_imports='from __future__ import annotations'" ]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
