default_language_version:
  python: python3

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        args: [ "--py38-plus" ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: setup.cfg
      - id: end-of-file-fixer
        exclude: ".ipynb"
      - id: check-json
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
      - id: debug-statements
      - id: pretty-format-json
        args: ['--autofix', '--no-ensure-ascii', '--no-sort-keys']
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [ 'flake8-rst-docstrings' ]
        args: [ '--config=setup.cfg' ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ '--settings-file=setup.cfg', "--add_imports='from __future__ import annotations'" ]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: [ '--config=setup.cfg' ]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
        args: [ '--config-file=.yamllint.yaml' ]