[tool.poetry]
name = "ncompare"
version = "1.0.0"
description = "Compare the structure of two NetCDF files at the command line"
authors = ["Daniel Kaufman <daniel.kaufman@nasa.gov>"]
readme = "README.md"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.scripts]
ncompare = "ncompare.console:main"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.2"
netCDF4 = "^1.6.0"
xarray = "^2022.6.0"
colorama = "^0.4.5"
openpyxl = "^3.0.10"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^3.7"
pylint = "^2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = "true"
default_section = "THIRDPARTY"
lines_after_imports = 2
combine_as_imports = "true"
